In [ ]:
import sys, os
_nb = globals().get("__vsc_ipynb_file__", "")
_root = os.path.abspath(os.path.join(os.path.dirname(_nb), "../..")) if _nb else os.getcwd()
if _root not in sys.path:
    sys.path.insert(0, _root)

In [1]:
from index_management.valuation.Manager import Valuation

In [2]:
value = Valuation(20250331, "cw")
df_weights = value.valuation_quarterly()
df_weights

      Symbol  NumShares
0      AC.PA    99358.0
1     ACA.PA  1281048.0
2      AI.PA   248712.0
3     AIR.PA   288143.0
4      BN.PA   291268.0
5     BNP.PA   453199.0
6     BVI.PA   186886.0
7      CA.PA   282298.0
8     CAP.PA    67590.0
9      CS.PA   951677.0
10     DG.PA   251229.0
11    DSY.PA   537848.0
12   EDEN.PA   109375.0
13     EL.PA   185043.0
14     EN.PA   168524.0
15   ENGI.PA  1097417.0
16    ERF.PA    79281.0
17    GLE.PA   323322.0
18     HO.PA    92296.0
19    KER.PA    46071.0
20     LR.PA   110053.0
21     MC.PA   184775.0
22     ML.PA   290128.0
23     MT.AS   298931.0
24     OR.PA   232395.0
25    ORA.PA  1215566.0
26    PUB.PA   107088.0
27     RI.PA   110955.0
28    RMS.PA    43378.0
29    RNO.PA   118807.0
30    SAF.PA   160586.0
31    SAN.PA   474100.0
32    SGO.PA   204645.0
33  STLAM.MI  1015183.0
34  STMPA.PA   349356.0
35     SU.PA   238201.0
36    TEP.PA    24774.0
37    TTE.PA   836860.0
38    UBLB.F  1184977.0
39    VIE.PA   310993.0

In [3]:
value = Valuation(20250331, "msr")
df_weights = value.valuation_quarterly()
df_weights

      Symbol  NumShares
0      AC.PA        0.0
1     ACA.PA  2863858.0
2      AI.PA   141876.0
3     AIR.PA   137330.0
4      BN.PA   581127.0
5     BNP.PA   667679.0
6     BVI.PA   534902.0
7      CA.PA  3368641.0
8     CAP.PA    13082.0
9      CS.PA  1311760.0
10     DG.PA   413089.0
11    DSY.PA        0.0
12   EDEN.PA   704034.0
13     EL.PA        0.0
14     EN.PA  1972397.0
15   ENGI.PA  2613718.0
16    ERF.PA   799370.0
17    GLE.PA  1133260.0
18     HO.PA   595252.0
19    KER.PA        0.0
20     LR.PA        0.0
21     MC.PA        0.0
22     ML.PA   213929.0
23     MT.AS   415342.0
24     OR.PA    50565.0
25    ORA.PA  3640497.0
26    PUB.PA        0.0
27     RI.PA        0.0
28    RMS.PA        0.0
29    RNO.PA    18202.0
30    SAF.PA    62836.0
31    SAN.PA   195816.0
32    SGO.PA    58125.0
33  STLAM.MI        0.0
34  STMPA.PA        0.0
35     SU.PA        0.0
36    TEP.PA   307945.0
37    TTE.PA   823404.0
38    UBLB.F  2131872.0
39    VIE.PA  2294747.0